name: Absent_present
description: A new Flutter project for class attendance management

publish_to: 'none' # Prevent publishing to pub.dev

version: 1.0.0+1
environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  hijri: ^1.0.0
  excel: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
